import { StyleSheet, Platform } from "react-native";
import { C } from "../../src/theme/colors";
import { shadow, shadowSm, shadowNav } from "../../src/theme/shadows";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: C.surface,
  },
  /* Header */
  header: {
    backgroundColor: C.surfaceBright,
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  avatarStack: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarBack: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.primaryFixed,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  avatarBackText: {
    color: C.onPrimaryFixed,
    fontSize: 14,
    fontWeight: "700",
  },
  avatarFront: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: C.tertiaryFixed,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: -16,
    borderWidth: 2,
    borderColor: C.surfaceBright,
    zIndex: 2,
  },
  avatarFrontText: {
    color: C.onTertiaryFixed,
    fontSize: 14,
    fontWeight: "700",
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: C.primary,
  },
  /* Scroll */
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  /* Couple Card */
  coupleCard: {
    backgroundColor: C.surfaceContainerLowest,
    borderRadius: 16,
    padding: 24,
    alignItems: "center",
    marginBottom: 24,
  },
  coupleAvatars: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    height: 64,
    marginBottom: 12,
    position: "relative",
    width: 120,
  },
  coupleAvatarA: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: C.avatarRed,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: 0,
    ...shadowSm,
  },
  coupleAvatarB: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: C.avatarTeal,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 0,
    borderWidth: 4,
    borderColor: C.surfaceContainerLowest,
    ...shadowSm,
  },
  coupleAvatarText: {
    color: C.onPrimary,
    fontSize: 24,
    fontWeight: "700",
  },
  coupleName: {
    fontSize: 16,
    fontWeight: "600",
    color: C.onSurface,
    textAlign: "center",
    marginBottom: 4,
  },
  coupleSubtitle: {
    fontSize: 14,
    color: C.onSurfaceVariant,
  },
  /* Metrics */
  metricsRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 24,
  },
  metricCard: {
    flex: 1,
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    aspectRatio: 1,
    ...shadowSm,
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: C.onPrimaryContainer,
    opacity: 0.9,
    marginBottom: 4,
  },
  metricValue: {
    fontSize: 14,
    fontWeight: "600",
    color: C.onPrimaryContainer,
  },
  /* Progress */
  progressCard: {
    backgroundColor: C.surfaceContainerLow,
    borderRadius: 12,
    padding: 16,
    marginBottom: 32,
  },
  progressTrack: {
    height: 12,
    backgroundColor: C.surfaceVariant,
    borderRadius: 6,
    overflow: "hidden",
    marginBottom: 12,
  },
  progressFill: {
    height: "100%",
    backgroundColor: C.progressGreen,
    borderRadius: 6,
  },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 4,
  },
  progressLabelTitle: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: C.onSurfaceVariant,
    marginBottom: 2,
  },
  progressLabelValue: {
    fontSize: 14,
    fontWeight: "700",
    color: C.onSurface,
  },
  /* Section Title */
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: C.onSurface,
    marginBottom: 12,
  },
  /* Actions Grid */
  actionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 32,
  },
  actionItem: {
    width: "30%",
    alignItems: "center",
    flexGrow: 1,
    flexBasis: "30%",
  },
  actionIconCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: C.surfaceContainerHigh,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
  },
  actionIconDanger: {
    backgroundColor: C.secondaryContainer,
  },
  actionLabel: {
    fontSize: 11,
    fontWeight: "500",
    color: C.onSurface,
    textAlign: "center",
    lineHeight: 14,
  },
  /* Expenses */
  expenseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  seeAllText: {
    fontSize: 12,
    fontWeight: "700",
    color: C.primary,
    letterSpacing: 0.6,
  },
  expenseList: {
    marginBottom: 24,
    gap: 8,
  },
  expenseItem: {
    backgroundColor: C.surfaceContainerLowest,
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    borderLeftWidth: 4,
    ...shadowSm,
  },
  expenseIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: C.surfaceContainerLow,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  expenseInfo: {
    flex: 1,
    marginRight: 8,
  },
  expenseTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: C.onSurface,
    marginBottom: 4,
  },
  expenseMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  expenseBadge: {
    backgroundColor: C.surfaceVariant,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  expenseBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: C.onSurfaceVariant,
  },
  expenseDate: {
    fontSize: 10,
    color: C.onSurfaceVariant,
  },
  expenseAmountCol: {
    alignItems: "flex-end",
  },
  expenseAmount: {
    fontSize: 14,
    fontWeight: "700",
    color: C.onSurface,
  },
  expensePayer: {
    fontSize: 10,
    color: C.onSurfaceVariant,
    marginTop: 2,
  },
  confirmBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.tertiaryContainer,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 6,
    gap: 2,
  },
  confirmBtnText: {
    color: C.onTertiaryContainer,
    fontSize: 11,
    fontWeight: "600",
  },
  /* Empty */
  emptyState: {
    alignItems: "center",
    paddingVertical: 32,
    marginBottom: 24,
  },
  emptyText: {
    fontSize: 14,
    color: C.onSurfaceVariant,
    marginTop: 12,
  },
  emptySubtext: {
    fontSize: 13,
    color: C.onSurfaceVariant,
    marginTop: 4,
    opacity: 0.7,
  },
  /* Banner */
  banner: {
    height: 180,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 24,
    backgroundColor: C.surfaceContainerHigh,
    justifyContent: "flex-end",
  },
  bannerOverlay: {
    backgroundColor: "rgba(0,0,0,0.35)",
    padding: 16,
  },
  bannerText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "700",
  },
  /* Sign Out */
  signOutBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
  },
  signOutText: {
    color: C.onSurfaceVariant,
    fontSize: 14,
    fontWeight: "500",
  },
  /* Bottom Nav */
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: C.surfaceContainerLowest,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    paddingTop: 8,
    paddingHorizontal: 16,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  navItemActive: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.primaryContainer,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 4,
    gap: 2,
  },
  navLabelActive: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: C.onPrimaryContainer,
  },
  navItem: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 4,
    gap: 2,
  },
  navLabel: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
    color: C.onSurfaceVariant,
  },
});
